trying new way to store private key - also fixed test errors

diff --git a/.github/workflows/validate-feature.yml b/.github/workflows/validate-feature.yml
--- a/.github/workflows/validate-feature.yml
+++ b/.github/workflows/validate-feature.yml
@@ -51,44 +51,53 @@ jobs:
           sfdx force
           sfdx plugins
 
-      # lint javascript for lwc's
+      # lint javascript for lwc's - need the first 2 npm commands to get
+      # the correct devDependencies from the package.json installed
       - name: Lint LWC
         id: lint-lwc
         run: |
           npm ci
           npm list --dev
-          npm run lint
+          sfdx scanner:run --target='**/lwc/**/*.js,**/aura/**/*.js' --engine retire-js
+          sfdx scanner:run --target='**/lwc/**/*.js,**/aura/**/*.js' --engine eslint --eslintconfig=force-app/main/default/lwc/.eslintrc.json
 
       # apex source scanner
       # https://forcedotcom.github.io/sfdx-scanner/en/scanner-commands/run/
       # rules are defined in the pmd/ruleset.xml
       # all possible rules are documented here: https://pmd.github.io/latest/pmd_rules_apex.html
       - name: Apex Source Scanner
-        id: analyze-apex
+        id: analyze-static
         run: |
-          sfdx scanner:run --target=force-app/main/default --engine pmd --pmdconfig "pmd/ruleset.xml" --format=json --severity-threshold=2 --outfile=analyze-apex.json || true
-          if test -f analyze-apex.json; then
+          sfdx scanner:run --target=force-app/main/default --engine pmd --pmdconfig='pmd/ruleset.xml' --format=json --severity-threshold=2 --outfile=analyze-static.json || true
+          if test -f analyze-static.json; then
             echo "ERROR: FIX THE PROBLEMS LISTED BELOW"
-            echo "analyze-apex.json = $(jq . analyze-apex.json)"
-            echo "::set-output name=error::Apex Source Scanner: Error = The source scanner found an Apex development standard violation. Please view the CI/CD log to see the issue(s)."
+            echo "analyze-static.json = $(jq . analyze-static.json)"
             exit 1
           fi
 
-      # TODO: IMPLEMENT SOME OF THE COOL NEW FEATURES DOCUMENTED HERE!!!
+      # use the source scanner to look for unused classes and methods
       # https://developer.salesforce.com/blogs/2023/02/boost-code-performance-with-salesforce-code-analyzer
+      - name: Apex Graph Engine
+        id: analyze-graph
+        run: |
+          sfdx scanner:run --target=force-app/main/default --projectdir ./ --engine sfge --format=json --outfile=analyze-graph.json || true
+          if test -f analyze-graph.json; then
+            echo "ERROR: FIX THE PROBLEMS LISTED BELOW"
+            echo "analyze-graph.json = $(jq . analyze-graph.json)"
+            exit 1
+          fi
 
       # authenticate to SF dev hub
-      # --username ${{ secrets.HUB_ORG_USER }}
       - name: Authenticate to Salesforce Dev Hub
         id: authenticate-devhub
         run: |
+          echo "${{ secrets.HUB_ORG_PRIVATE_KEY }}" > server.key
           sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_ORG_CLIENTID }} --username ${{ secrets.HUB_ORG_USER }} --jwtkeyfile server.key --setalias hub --setdefaultdevhubusername --json > auth.json || true
           echo "auth.json = $(jq . auth.json)"
           status=$(jq -r '.status' auth.json)
           if [ $status -ne 0 ]; then
             msg=$(jq -r '.message' auth.json)
             echo "error = $msg"
-            echo "::set-output name=error::$msg"
             exit 1
           else
             sfdx force:org:list
@@ -103,7 +112,6 @@ jobs:
           status=$(jq -r '.status' scratch.json)
           if [ $status -ne 0 ]; then
             msg=$(jq -r '.message' scratch.json)
-            echo "::set-output name=error::${msg}"
             echo "error = $msg"
             echo "error = ${{ steps.create-scratchorg.outputs.error }}"
             exit 1
@@ -122,7 +130,6 @@ jobs:
           status=$(jq -r '.status' deploy.json)
           if [ $status -ne 0 ]; then
             msg=$(jq -r '.message' deploy.json)
-            echo "::set-output name=error::${msg}"
             echo "error = $msg"
             echo "error = ${{ steps.deploy-source.outputs.error }}"
             exit 1
@@ -157,7 +164,6 @@ jobs:
                 msg+="$(_jq '.Message')\ $(_jq '.StackTrace')\ "
               fi
             done
-            echo "::set-output name=error::Run All Tests: Errors = ${msg}"
             exit 1
           fi
 
